swagger: "2.0"
info:
  version: "0.0.1"
  title: User Management App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: "/"
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  "/users":
    post:
      tags:
      - Users
      description: Create new user in system
      parameters:
      - name: user
        in: body
        description: User that we want to create
        schema:
          "$ref": "#/definitions/User"
      produces:
      - application/json
      responses:
        '200':
          description: New user is created
          schema:
            "$ref": "#/definitions/User"
    get:
      tags:
      - Users
      summary: Get all users in system
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Users"
    
  "/users/{id}":
    parameters:
    - name: id
      in: path
      required: true
      description: ID of user that we want to find
      type: string
    get:
      tags:
      - Users
      summary: Get user with given ID
      responses:
        '200':
          description: User is found
          schema:
            "$ref": "#/definitions/User"
    delete:
      summary: Delete user with given ID
      tags:
      - Users
      responses:
        '200':
          description: User is deleted
          schema:
            "$ref": "#/definitions/User"
    put:
      summary: Update user with give ID
      tags:
      - Users
      parameters:
      - name: user
        in: body
        description: User with new values of properties
        schema:
          "$ref": "#/definitions/User"
      responses:
        '200':
          description: User is updated
          schema:
            "$ref": "#/definitions/User"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User:
    required:
    - email
    properties:
      name:
        type: string
      age:
        type: number
        uniqueItems: true
      email:
        type: string
        uniqueItems: true
      phone:
        type: number
  Users:
    type: array
    items:
      properties:
        name:
          type: string
        age:
          type: number
          uniqueItems: true
        email:
          type: string
          uniqueItems: true
        phone:
          type: number